# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/gunnar/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),gunnar)

$(call add-radio-file-sha1-checked,radio/abl.img,2af16f6ec356ccbef3c25937d3dba1187e51096e)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,810a48f442b1cb6a8eb08a87a1b87a5165b5baac)
$(call add-radio-file-sha1-checked,radio/core_nhlos.img,38719c4ca1534c078aef21d6bac0976f785ba9a8)
$(call add-radio-file-sha1-checked,radio/devcfg.img,64542270eb6dc038ff92364731607b7a63107306)
$(call add-radio-file-sha1-checked,radio/dsp.img,b1512787b130b7f9907aab41a05e471db8452675)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,dde4d1ba8212091d9f4148e665c7a2f80a39ec13)
$(call add-radio-file-sha1-checked,radio/hyp.img,cd675ea15c2a98e5c1d5e3a4aecbb6473b184cc6)
$(call add-radio-file-sha1-checked,radio/imagefv.img,ef559e00f8ef835107efea4903d77b329587af25)
$(call add-radio-file-sha1-checked,radio/keymaster.img,adf67cdfd89ca63b4ffa728918251e3b6dbcd60e)
$(call add-radio-file-sha1-checked,radio/modem.img,acbb531dc3f42ea1c8c8f5d404fd32c9cd0dc6c9)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,611818027635a560cf56f608943533a9560a7c50)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,1b8085a9b344a5ec0245c812ec2c9dab29e39bb7)
$(call add-radio-file-sha1-checked,radio/qupfw.img,4f1204c2f5cd7b82a5eb6af8074b70437b41e34c)
$(call add-radio-file-sha1-checked,radio/rpm.img,5bb0b4b1ac84cb8f1566017901fc78fdf54ab60a)
$(call add-radio-file-sha1-checked,radio/splash.img,a0be6e8c3976ea6b31fcf07fdf037c66613eca21)
$(call add-radio-file-sha1-checked,radio/tz.img,a1f394b00e08075d333c6ef273892d60fd50a253)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,de6a3425e73f412c4285714d712481f03945f190)
$(call add-radio-file-sha1-checked,radio/xbl.img,452a9378bad296b15c525c0cfd27516c60a09193)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,2e670338a24273214b21c80b74c779d9dca70fe6)

endif
